### ISSUE TITLE
Shouldn't class names be uniform in Muses?

### ISSUE THREAD

**Issue by JJ** [MusesProject/Muses-Security-Quiz#1]
And use the musesproject.eu namespace instead of unige.ch?

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---------------------------------------------------------------------------------------------------------------------------


This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es



Nota: Esta es una respuesta autom�tica a su mensaje  "[Muses-Security-Quiz]
Shouldn't class names be uniform in Muses? (#1)" enviado el 23/03/2015
9:52:42.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.
