### ISSUE TITLE
Make a more explanatory README.md

### ISSUE THREAD

**Issue by JJ** [MusesProject/Muses-Security-Quiz#2]
With, at least, a short description of what this is about and installation and running instructions.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---------------------------------------------------------------------------------------------------------------------------


This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es



Nota: Esta es una respuesta autom�tica a su mensaje  "[Muses-Security-Quiz]
Make a more explanatory README.md (#2)" enviado el 23/03/2015 9:58:35.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by JJ** [comment]
@xaviertiti it's a bit better, but it should at least include installation and running instructions, how to file a bug report, and so on...
